### ISSUE TITLE
Auto publish on npm when merging a change to `main`

### ISSUE THREAD

**Issue by nhoizey** [tweetback/tweetback-canonical#11]
I have a GitHub Action for one of my Eleventy plugins that publishes the package on npm when I create a release in the GitHub repository:
https://github.com/nhoizey/eleventy-plugin-auto-preload/blob/main/.github/workflows/publish.yml

Would it be useful here?

**Comment by nhoizey** [comment]
Should be done with #20, but in dry-run mode for first try

**Comment by nhoizey** [comment]
@zachleat `npm ci` requires having the `package-lock.json` file in the repository.

This is what I do on all my projects to make sure dependencies always have the same versions on different environments.

It looks like you don't have the same habit, could you explain why you put it in `.gitignore`?

**Comment by zachleat** [comment]
I don’t really have a great reason, other than I like to have the latest minor versions of packages—feel free to check it in here!

**Comment by nhoizey** [comment]
Ok.

I agree it's more convenient, but unfortunately minor versions sometimes introduce issues, so CI needs exactly the same versions.

**Comment by nhoizey** [comment]
@zachleat I've had some issues with npm and GitHub tokens for package publication, but it should now work.

Commit messages have to start with `mapping: ` to be considered for a new release, I've added the information both in the README and a Pull Request template

**Comment by nhoizey** [comment]
Packages are now created on npm:
https://www.npmjs.com/package/@tweetback/canonical/v/2.0.6

As well as releases on GitHub:
https://github.com/tweetback/tweetback-canonical/releases/tag/v2.0.6

Unfortunately, there's an issue in the `semantic-release` package, so the Action result is an error even if the most important tasks are successful:
https://github.com/semantic-release/semantic-release/issues/2204

**Comment by nhoizey** [comment]
Closing, as there has been no issue for 2 weeks, and multiple merges, now.
