### ISSUE TITLE
Add more devs to have npm publish rights

### ISSUE THREAD

**Issue by zachleat** [tweetback/tweetback-canonical#9]
@nhoizey do you have an `npm` account? I’m the only one with publish access here 

https://www.npmjs.com/package/@tweetback/canonical

https://www.npmjs.com/settings/tweetback/teams

**Comment by nhoizey** [comment]
@zachleat yes, I'm here: https://www.npmjs.com/~nhoizey

**Comment by zachleat** [comment]
Invitation sent!

**Comment by nhoizey** [comment]
And accepted! 🙏

**Comment by nhoizey** [comment]
@zachleat so should we publish a new release every time someone adds a mapping, or daily, or just from time to time?

What about easing the process?
- #11

**Comment by nhoizey** [comment]
Ok, I'll automate this. 👍

We could add a test to automatically block a PR if the JSON is not good (missing `"` or `,` for example), at least.
